### PR TITLE
Adds note about enclosures.

### LINKED ISSUE #671: Add a link to this in the README?
http://vsby.co/work/auction-kiosk

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #671.

### CODE REVIEW

**Comment by ashfurrow** [comment]
@orta Does Peril have an org-wide ignore list?

**Comment by orta** [comment]
@ashfurrow  - yeah, [here](https://github.com/artsy/artsy-danger/blob/master/spellcheck.json), 

weird bit is that it should actually include READMEs

**Comment by orta** [comment]
oh, it doesn't that's OK, this is fine, will see where it goes

**Comment by orta** [comment]
the dupe is a bit worrying though

**Pull request merged**
