### PR TITLE
@orta => Fixes messaging surrounding cancel/back button titles

### LINKED ISSUE #373: Adding a "Confirm" or "Close" button to the highest bid screen
To exit screen you have to click "Cancel" in the upper left-hand corner. You can't click out by tapping outside the screen. Makes bidders think they're canceling their high bid. 

img_0014

### PR DESCRIPTION
**Pull request by ashfurrow**
We don't want to confuse users by having a button entitled "Cancel" on a confirmation screen. 

This needs:

- Better abstraction in the long-term (#406)
- Regenerated snapshots, that I can't do since I don't have the 8.1 simulator at home and my internet is :dog: slow (#405)

Fixes #373, and a small typo.

### CODE REVIEW

**Comment by orta** [comment]
This is great, shame about them reds.

**Comment by orta** [comment]
MRW when my SO doesn't want sexy time after I've done all the chores.

**Comment by ashfurrow** [comment]
Now that I'm in the office, I'll regenerate the snapshots.

**Comment by ashfurrow** [comment]
But yeah, still a shame.

**Pull request merged**
