### PR TITLE
@orta => Updates Things

### LINKED ISSUE #440: Updates to Fastlane will break
https://github.com/artsy/eidolon/blob/master/fastlane/Fastfile#L72

This has been removed in a later release of fastlane. Just a warning if you `bundle update`, I had to remove it on mine.

### PR DESCRIPTION
**Pull request by ashfurrow**
Started as a Fastlane update, since `desc` calls added by @KrauseFx were breaking CI, but then I figured why not go _all the way_. 

Fixes #440.

### CODE REVIEW

**Comment by orta** [comment]
red?

**Comment by orta** [comment]
Could be legit: 

```
INFO [2015-05-08 18:06:27.53]: [SHELL OUTPUT]: ⌦  /Users/travis/build/artsy/eidolon/Kiosk/Supporting Files/PodsBridgingHeader.h:31:9: 'CardFlight/CardFlight.h' file not found
```

Sidenote, @KrauseFx I really think there's too much going on in these logs. Can the build/test lanes be set to not have so much prefixed text (`INFO [2015-05-08 18:06:27.53]: [SHELL OUTPUT]:` takes up half the space on a line in travis )

**Comment by KrauseFx** [comment]
@orta I'm okay with changing the output format. I assume you're not only talking about removing the `[SHELL OUTPUT]` but also the date/time before? 

[date output](https://github.com/KrauseFx/fastlane_core/blob/master/lib/fastlane_core/helper.rb#L15) and [shell command](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/actions_helper.rb#L77) code

**Comment by ashfurrow** [comment]
Oops – will fix tonight.

**Comment by ashfurrow** [comment]
This is weird; the compiler can't find the CardFlight header file anymore (it's failing locally, too, after I cleaned the build folder). Investigating.

**Comment by ashfurrow** [comment]
Huh – I don't actually see the CardFlight pod listed in the Pods project. 

screen shot 2015-05-09 at 7 04 43 pm

Gonna check the CocoaPods release notes to see if something changed around subspecs. The [CardFlight podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/CardFlight/1.9.2/CardFlight.podspec.json) does that "empty pod with default podspec" thing.

**Comment by ashfurrow** [comment]
Could it be that it doesn't have any implementation files? Just a `.a` with accompanying headers?

**Comment by orta** [comment]
Travis Pod Caching?

**Comment by ashfurrow** [comment]
Don't think so – it's failing locally, too.

**Comment by ashfurrow** [comment]
Yeah, I think it's because there are no implementation files. I added `GoogleAnalytics-iOS-SDK` to the podfile, ran `pod install`, but it's not listed in the Pods project.

**Comment by ashfurrow** [comment]
Looks like a [known issue](https://github.com/CocoaPods/CocoaPods/issues/3499); I've got to go right now, but I'll take a look at the conversation there for a workaround.

**Comment by ashfurrow** [comment]
Hmm. Maybe not.

**Comment by orta** [comment]
:+1:

**Pull request merged**
