### PR TITLE
@1aurabrown => Updates to CocoaPods 0.36 Beta 1

### PR DESCRIPTION
**Pull request by ashfurrow**
In the process of writing that blog post, I thought it'd be prudent to update to the new CocoaPods beta. 

The project doesn't currently build – the compiler segfaults. It looks similar to the error we were getting in XCGLogger when optimizations turned on, so through some trial-and-error, I figured out that it was the `Pods` target itself. Disabling compiler optimization for this target fixed the segfaults – maybe something in cocoapods-keys? 

- [ ] ~~Disable `Pods` optimizations using post-install hook~~
- [x] Fix UIFonts pod (the resource files aren't being accessed properly, causing a runtime crash)
- [x] Investigate why compiler is segfaulting on first-pass but succeeding on subsequent builds

At any rate, I think including an example of how to disable optimizations on a specific pod would be :+1: in the blog post.

### CODE REVIEW

**Comment by orta** [comment]
also, rebase

**Comment by ashfurrow** [comment]
I expect that this CI build will segfault. It's on my todo list in the PR description.

**Comment by ashfurrow** [comment]
@mrackwitz It looks like it might be a problem with ReactiveCocoa, or possibly Moya. The first time I try and build, the compiler segfaults with "Cannot define category for undefined class 'RACSignal'":

```
/Users/ash/Library/Developer/Xcode/DerivedData/Kiosk-dywhoqbddoimmpfuccrbwpyyoagk/Build/Products/Debug-iphonesimulator/Pods/Moya.framework/Headers/Moya-Swift.h:72:12: error: cannot define category for undefined class 'RACSignal'
@interface RACSignal (SWIFT_EXTENSION(Moya))
           ^
/Users/ash/bin/eidolon/Pods/ReactiveCocoa/ReactiveCocoa/Objective-C/NSData+RACSupport.h:12:8: note: forward declaration of class here
@class RACSignal;
       ^
<unknown>:0: error: could not build Objective-C module 'Moya'
```

But subsequent builds succeed without the error. If I clean the build folder, I get the segfault again on the first build. 

I'm going to look into the Moya project. It has ReactiveCocoa as [a dependency](https://github.com/ashfurrow/Moya/blob/1107efc877fdca15e44f8947f7efb65c72017693/Moya.podspec#L22), and I have ReactiveCocoa above Moya/Reactive in my podfile.

**Comment by ashfurrow** [comment]
So frustrating. 

screen shot 2015-01-06 at 11 25 02 am

**Comment by ashfurrow** [comment]
Looks like Travis is getting the same errors I am: https://travis-ci.org/artsy/eidolon/builds/46053263#L780-L782 The file producing the error appears to have been created by the Swift compiler. It's almost like the `@import ReactiveCocoa;` isn't being included – maybe the `#if defined(__has_feature) && __has_feature(modules)` is failing? 

@mrackwitz Is there any way to influence how this file is created? 

```objc
// Generated by Swift version 1.1 (swift-600.0.56.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ReactiveCocoa;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface RACSignal (SWIFT_EXTENSION(Moya))
- (RACSignal *)filterStatusCode:(NSInteger)code;
- (RACSignal *)filterSuccessfulStatusCodes;

/// Maps data received from the signal into a UIImage. If the conversion fails, the signal errors.
- (RACSignal *)mapImage;

/// Maps data received from the signal into a JSON object. If the conversion fails, the signal errors.
- (RACSignal *)mapJSON;

/// Maps data received from the signal into a String. If the conversion fails, the signal errors.
- (RACSignal *)mapString;
@end

#pragma clang diagnostic pop
```

**Comment by ashfurrow** [comment]
From what I understand, `import ReactiveCocoa` in the Moya files should give me access to all of ReactiveCocoa's classes (I've double-checked that ReactiveCocoa's umbrella header contains all of the header files). If I navigate to the Moya `import` statement, I see the following error:

```
Cannot load underlying module for 'ReactiveCocoa'
```

**Comment by ashfurrow** [comment]
Also strange that the compiler error is "could not build Objective-C module 'Moya'".

**Comment by ashfurrow** [comment]
Couldn't figure out why this was segfaulting. I tried to reproduce the issue in a new project and couldn't, so I just recreated the Kiosk Xcode project from scratch. Shouldn't be any problems, eh @orta? 

OK, so the tests are now *failing*, not *erroring*, which is definitely a :+1: And they're only failing because of some weird Travis issue:

> 2015-01-06 17:43:08.632 xcodebuild[23326:4503]  iPhoneSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.

Looking into that now.

**Comment by ashfurrow** [comment]
Since @orta is mostly unavailable this week, I'm going to reassign this to @1aurabrown – feel free to merge when you think it's good to go.

**Comment by orta** [comment]
This looks good from my side, merggggging

**Comment by orta** [comment]
MRW I check to see if that cop saw me speeding.

**Pull request merged**
