### PR TITLE
@alloy => Manual CC Entry Problem 📱

### LINKED ISSUE #455: Swallowed error on entering cc
Witnessed a user register, enter a cc, then enter an expiration date, then hit ok and get nothing back. Spinner spinned, then the button came back clickable without any errors. CC seems to have been entered into the system. The only workaround was to take someone's bid on an ipad. Trying to bid again on a kiosk was asking for the cc again, didn't retry.

### PR DESCRIPTION
**Pull request by ashfurrow**
Crus is that we weren't sending a "complete" event to our `finishedSignal` once the CC tokenization succeeded. I added tests to ensure that the event is sent if and only if the tokenization succeeds. 

I also noticed a few other problems that I fixed and added test for, in separate commits. Should I make things like that separate PRs? Open to advice.

(Note: Circle and Travis are currently both failing to run tests. I've checked that they pass locally.)

Fixes #455.

### CODE REVIEW

**Comment by alloy** [comment]
Tested for real/device?

**Comment by ashfurrow** [comment]
I've not tested it on a device yet; will do after lunch.

**Comment by ashfurrow** [comment]
(Thanks for the reminder!)

**Comment by alloy** [comment]
Alrighty then, I’ll wait to hear when you tested it on device.

Regarding splitting off PRs, I’m ok with this personally. If you feel wrong and it would keep you up at night you could just do the fix and then a new PR with all the ‘UI’ issues you came across.

**Comment by ashfurrow** [comment]
Separate PRs are hard since sometimes the fixes I do depend on the other code I've already changed for the main issue. Gonna keep it like this, in small commits :+1:

**Comment by alloy** [comment]
@ashfurrow To be clear, I meant that I’m personally ok with not splitting off, i.e. as-is.

**Comment by ashfurrow** [comment]
@alloy verified on device.

**Comment by alloy** [comment]
:100: :+1:

**Comment by alloy** [comment]
Oh, forgot to notice before, but CHANGELOG?

**Comment by ashfurrow** [comment]
Knew there was something I was forgetting.

**Comment by alloy** [comment]
:100: +1 :+1:

**Pull request merged**
