### PR TITLE
Update Logger.swift to handle NSFileHandle throws

### PR DESCRIPTION
**Pull request by AndrewSB**
@ashfurrow you must have missed this in https://github.com/artsy/eidolon/commit/86d2fd2c2604e5e0bff6d8579b5a0e91af8fc70b

### CODE REVIEW

**Comment by orta** [comment]
Nice spot 👍

**Comment by ashfurrow** [comment]
Thanks! The CI failure looks unrelated to this PR, I'll open a separate issue to fix it. Thanks again for the patch!

**Comment by AndrewSB** [comment]
😀

**Comment by AndrewSB** [comment]
Thank you so much for all of your work, both of you. I've learned *so* much pouring over your codebase this weekend!

**Pull request merged**
