### PR TITLE
@alloy => No longer render markdown links

### LINKED ISSUE #375: Markdown renders links
When rendering markdown, we ought to remove the links, which don't work and might confuse users.

### PR DESCRIPTION
**Pull request by ashfurrow**
This is a WIP until @xing can take a look at https://github.com/xing/XNGMarkdownParser/pull/5 

Fixes #375.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Merged, waiting on a minor release on the pod to avoid pointing at my fork.

**Comment by ashfurrow** [comment]
Un-WIP'd. Thanks @pietbrauer!

**Comment by pietbrauer** [comment]
Sure :cat2:

**Comment by alloy** [comment]
No more lynx! :+1:

**Comment by alloy** [comment]
(I’m assuming the second CI run passing means it’s green?)

**Comment by ashfurrow** [comment]
Yeah, we're looking into Travis problems. I've contacted them. We'll see.

**Comment by ashfurrow** [comment]
The two different results indicate, to me, an intermittent problem with Travis. Looks like it's often unable to boot the simulator.

**Pull request merged**
