### PR TITLE
Bypass credit card swipe requirement

### PR DESCRIPTION
**Pull request by ashfurrow**
This PR is work for [PURCHASE-602](https://artsyproduct.atlassian.net/browse/PURCHASE-602). It is blocked by [this Gravity PR](https://github.com/artsy/gravity/pull/11986). Here's what we did:

- Added bypass flag to `Sale` model.
- Updated registration UI to no longer ask for CC on flagged sales.
- Updated bidding logic to no longer prompt users with no credit cards to swipe one (on flagged sales).
- Updated some error-handling code surrounding `param_error` (we no longer assume all `param_error`s are outbid errors).
- We fixed a bug where users logging in with a paddle number + PIN were sometimes asked for their Artsy password (I checked with Nicole).

### CODE REVIEW

**Comment by ashfurrow** [comment]
Looks like Circle isn't picking up web hooks, probably since it thinks we're still on Circle CI 1.0. I've cherry-picked the merge commit from #697 into master to try to get it working: https://github.com/artsy/eidolon/commit/fff74c73f40fa3c32dff0073d8b1b63a55ee0c18

**Comment by ashfurrow** [comment]
Okay! Finally did it. I stopped and re-added the project, to no effect. In the end, updating the Circle config in 
https://github.com/artsy/eidolon/pull/698/commits/76d556a72679e59d208a59894ec96067e72b980 8 did it :)

**Comment by ashfurrow** [comment]
Just realized I only tested the bid flow on this, not the registration flow. Might need a small tweak.

**Comment by orta** [comment]
Cool, yeah, this looks good to me 👍

**Pull request merged**
