### PR TITLE
[⛳] Addresses feedback

### PR DESCRIPTION
**Pull request by ashfurrow**
This wraps up the code-golfing. On to testing! Or blogging or what-have-you.

### CODE REVIEW

**Comment by orta** [comment]
:+1: def, mergable on green.

**Comment by ashfurrow** [comment]
Travis is having OS X build problems, this can wait.

**Comment by ashfurrow** [comment]
Restarted the build. Second time I've seen this intermittent failure: 

```
 failed - expected to equal <2015-12-04 20:30:43 +0000>, got <2015-12-04 20:30:43 +0000>
```

I'll look into it. Could be a Nimble bug or something.

**Comment by ashfurrow** [comment]
Running through a staging auction, there are only a few small issues I need to address. Largely, everything look :ok: I suspect one issue might be related to the inconsistent test auction we use; I'll get some help from Alessandra to do a thorough run-through :)

**Pull request merged**
