### PR TITLE
Trying CircleCI debugging thing.

### PR DESCRIPTION
**Pull request by ashfurrow**
Apparently [this](https://devforums.apple.com/message/1125867#1125867) fixes the sim launch problems.

### CODE REVIEW

**Comment by ashfurrow** [comment]
``` no rule to process file '/Users/distiller/eidolon/Pods/CocoaPodsKeys/Keys.podspec.json' of type text.json for architecture x86_642015-07-01 09:00:43.480 
```

Update CocoaPods-Keys should fix that. The Circle people seemed to think it may be causing the problem.

**Comment by orta** [comment]
That shouldn't be failing the build though, that's a warning, think it's still in there

**Comment by ashfurrow** [comment]
It's a simulator launch problem – the doesn't fail, it just times out :( Bit of a hail marry :shrug:

**Comment by ashfurrow** [comment]
Contacted them again – hoping to hear back soon.

**Pull request closed without merging**
