### PR TITLE
[WIP] integrate an external networking stack

### PR DESCRIPTION
**Pull request by AndrewSB**
Hey @ashfurrow!

A little embarrassing to admit, but I was having trouble setting up the repo with cocoapods. I've never really used cocoapods before. When you have some time, could you point me in the right direction with https://github.com/AndrewSB/Networking/issues/1?

### CODE REVIEW

**Comment by orta** [comment]
I'm a bit wary of adding a new dependency that is 3 days old and doesn't have a README...

Especially one where we would end up having to add CocoaPods support - was there some discussion around this that I've not seen?

**Comment by ashfurrow** [comment]
Yeah, I asked for a PR to discuss what could be abstracted from Eidolon for the purposes of illustrating what Moya and RxSwift could do together.

**Comment by ashfurrow** [comment]
@AndrewSB I can't remember where we landed on this, should we keep this open or close it?

**Comment by AndrewSB** [comment]
I'm not sure, I can't remember either. I'll leave it up to you 👍

I think something separate might be easier to digest for people like the author of https://github.com/Moya/Moya/issues/936
But I think the separate repo should be under Moya, and not my user, IF we are to make it.

**Comment by pedrovereza** [comment]
@ashfurrow @AndrewSB I think you both agreed that extracting these things to a repo was an overkill (see [here](https://github.com/Moya/Moya/issues/722#issuecomment-266578494)).

I feel the overall conclusion was that having something like [AndrewSB/Networking](https://github.com/AndrewSB/Networking) is useful for Moya contributors to team up and solve common use cases and use the repo as reference for good practices.

However, I think the idea of integrating it with Eidolon was discarded (too small, overkill, etc).

**Comment by ashfurrow** [comment]
Cool, gonna close then, thanks!

**Pull request closed without merging**
