### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by dkhamsing**
These links have changed

### CODE REVIEW

**Comment by orta** [comment]
Nice sleuthing!

**Comment by dkhamsing** [comment]
:smile: 
I am experimenting with ruby 

https://github.com/dkhamsing/frankenstein/tree/dev
https://github.com/dkhamsing/frankenstein

**Comment by orta** [comment]
clever! Looks really useful, would want this on our blog.

**Comment by dkhamsing** [comment]
thx
it's kind of a mess.. any tips welcome https://github.com/dkhamsing/frankenstein/blob/dev/lib/frankenstein.rb

**Pull request merged**
