### PR TITLE
@ashfurrow : add CVV to manual card entry

### PR DESCRIPTION
**Pull request by acjay**
Due to my simulator seemingly not connecting to staging auctions, I haven't been able to actually try this on my own, so it may not quite work. I tried to write it completely analogously to existing code.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool, about to hop on a plane – will take a look when I land. How did the other PR go, for polling?

**Comment by acjay** [comment]
Fixed one problem here but there's still another problem of a couple bad snapshots. Not sure how we update those.

**Comment by ashfurrow** [comment]
Easiest way to update them is to use @orta's Xcode plugin: http://github.com/orta/snapshots/

**Comment by acjay** [comment]
Whoa, plugins! This could be a gamechanger. What do you and @orta recommend?

**Comment by ashfurrow** [comment]
Nothing besides the one that Orta made – he probably has other recommendations :)

**Comment by ashfurrow** [comment]
Should be able to pull the same trick with rebasing as #520 to test against staging.

**Comment by acjay** [comment]
Alright fixed the keys and the Podfile, but still can't see the live test auction

**Comment by ashfurrow** [comment]
That is so bizarre! Just to confirm, you did a rebase from master, then a `pod install`, and then ⌘R to re-run the app?

**Comment by ashfurrow** [comment]
That is so bizarre! Just to confirm, you did a rebase from master, then a `pod install`, and then ⌘R to re-run the app?

**Comment by acjay** [comment]
I merged master, but yes

**Comment by ashfurrow** [comment]
And a `pod install` prompted you for keys?

**Comment by acjay** [comment]
Yep, I entered all the most recent keys

**Comment by ashfurrow** [comment]
(For the record, Alan and I resolved this in Slack – a clean build in Xcode solved things.)

**Comment by ashfurrow** [comment]
I've fixed most of these – just two failing snapshots I'm looking at now.

**Comment by ashfurrow** [comment]
OK so this should be good to go. @acjay feel free to revert this PR if the changes ( https://github.com/artsy/eidolon/commit/14db2b64891278731f4b6bd9c7d55bec99ded7a5 ) don't make sense – I only had to modify a few tests, and remove one that no longer made sense with CVV entry. 

During the next mock auction, I'd appreciate it if someone could swipe an actual credit card on production (just registering!) to verify 100% that the CVV stuff works against Stripe production and the APIs changes for trusting CCs.

**Pull request merged**
