### PR TITLE
Updates to Xcode 8.2

### PR DESCRIPTION
**Pull request by ashfurrow**
Despite running on identical iOS versions, running Xcode 8.1 on CI and 8.2 locally was giving me different snapshot results. You can see the slight differences here:

screen shot 2017-02-08 at 10 41 09 am

If I had to guess, I'd bet that the Swift language update in Xcode 8.2 changed how floating point rounding or division works, in some arcane way.

### CODE REVIEW

**Comment by orta** [comment]
hrm, I'm assuming this fail is the opposite of the what you've just changed :/

**Comment by orta** [comment]
https://eidolon-ci.s3.amazonaws.com/192/index.html

**Comment by orta** [comment]
I rebuilt it without cache - let's give it another shot

**Comment by ashfurrow** [comment]
Yeah, I'm not sure what's going on – thanks!

**Comment by ashfurrow** [comment]
Well, looks like it's behaving differently on my local machine regardless of Xcode version. Hmm.

**Comment by orta** [comment]
64v32 sim?

**Comment by ashfurrow** [comment]
Nah, they're both iPad Air 2's. I'll try rebooting I guess 😛

**Comment by ashfurrow** [comment]
Quite upset at the fact, but I must admit that rebooting worked.

**Pull request closed without merging**
